### ISSUE TITLE
Cannot retrieve refresh Token

### ISSUE THREAD

**Issue by SwapFaceL** [bluewalk/lidlplus-php-client#2]
Hey,

sadly it is not working as it seems the method was changed. When using the MITM proxy the app is not working as if there is no connection. Tried to login through the website but no success on sniffing the token.

Any ideas?
![Screenshot from 2020-10-25 13-55-27](https://user-images.githubusercontent.com/35925904/97107817-cee0ab00-16c9-11eb-8cbd-a4da732f1fd5.png)

**Comment by bluewalk** [comment]
They have introduced certificate pinning, so MITM won't work anymore.
What you can do is use the Android APK, patch that to remove certificate pinning and use MITM to fetch the refresh token.

I have not yet found an endpoint to fetch a new refresh token. Good thing is that once you have the refresh token, it won't expire.

**Comment by SwapFaceL** [comment]
Thanks, after some research I already realized that this might be the problem. I will soon try to patch the APK acoordingly and if I find an endpoint or mechanism to fetch this token I will let you know.
Would be much easier for users to just use their credentials ;)

Thanks again for the hint.

**Comment by bluewalk** [comment]
I totally agree, it would make things a lot easier ;)

You can give the following script a shot as well, curious if it works: https://gist.github.com/basst85/ef5dae992f75ca4773a75f0249583bc1

**Comment by SwapFaceL** [comment]
Found that yesterday already but could not make it work with Node. But thats probably an issue on my side with the version, throws an BigInt issue all the time which I can't solve and I was not able to rewrite it properly. But later this week I will spend some time to find a solution.

**Comment by SwapFaceL** [comment]
I spend some time on cert unpinning but without final success.
Followed the tutorial:
https://medium.com/@ved_wayal/hail-frida-the-universal-ssl-pinning-bypass-for-android-e9e1d733d29
And combined it with mitm-Proxy in transparent mode.

No success, however it seems to be more a problem with the proxy itself.
The cert unpinning worked like a charm in combination with genymotion personal edition.

**Comment by SwapFaceL** [comment]
I tried a different approach and decompiled the APK, started refactoring a lot of variables, methods and classes. But haven't found the concrete part where the refreshToken is generated.

I assume the concrete HTTPS-Request is somewhere in "sources\net\openid\appauth\", thats where I refactored most of the classes.

http://www.filedropper.com/lidlplusv14261apkpurecomsourcefromjadx

**Comment by SwapFaceL** [comment]
Okay so I managed to retrieve the token finally with adjusting the script you mentioned.
It works now to retrieve the token, however if I just use it in your code:
```
$lidl = new Net\Bluewalk\LidlPlus\LidlPlus('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
$receipts = $lidl->GetReceipts();
print_r($receipts)
```
The output is:
```
stdClass Object ( [message] => Mandatory update [code] => RESULT_006 )
```
I ensured that the json-file can be created to store the token.

any ideas @bluewalk ?

**Comment by bluewalk** [comment]
@SwapFaceL That's great news, will you share the updated version of that script for future users?

I have also updated the code as it had the same "bug" my C# client had, the app version. Can you give it another shot?

**Comment by SwapFaceL** [comment]
Thanks for the fast reply & update. As soon as I am sure that everything works I will share the script for usage ;)

So with you updated code the error disappeared, but I cannot seems like I get nothing returned:
```
stdClass Object ( [page] => 0 [size] => 0 [totalCount] => 0 [records] => Array ( ) )
```
In the app are at least 5 records.

**Comment by bluewalk** [comment]
That's idd, I am using the following code to show my last receipt:

```php
require_once __DIR__ . '/vendor/autoload.php';

$lidl = new Net\Bluewalk\LidlPlus\LidlPlus('mykey');
$receipts = $lidl->GetReceipts();

$latest = $lidl->GetReceiptJpeg($receipts->records[0]->id);

header('Content-type: image/jpeg');
print $latest;
```

**Comment by SwapFaceL** [comment]
Finally managed to solve it, it was because you are a dear neighbour from the netherlands :D Seems like the records are stored per country, so I needed to go through another gateway for germany. 

I will share everything as soon as I am done ;) thanks for the help so far!
