### ISSUE TITLE
endpoints still invalid

### ISSUE THREAD

**Issue by Suresh-Subedi** [bluewalk/lidlplus-php-client#6]
Still, old endpoint is used for receipts.

When I try to get receipts for Belgium I get:
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>
```

https://appgateway.lidlplus.com/tickets/api/v1/be/list/1 gives error above
https://appgateway.lidlplus.com/app/v24/be/tickets/list/1 gives internal server error

is it still working for you guys? are you getting receipts for your countries with above urls?

**Comment by bluewalk** [comment]
Yes the endpoint has changed once again, I had already changed it for the .NET library but haven't had the time for this one yet. Will try to fix later :)

**Comment by bluewalk** [comment]
Can you check the code in the [updated-endpoints](https://github.com/bluewalk/lidlplus-php-client/tree/updated-endpoints) branch? I am unable to test at the moment but want to be sure before pushing it to Packagist.

**Comment by Suresh-Subedi** [comment]
Semicolon is missing in LidlPlus.php at line 9.
Get receipts url must be missing country code, I get not found.
With endpoint  https://tickets.lidlplus.com/api/v1/be/list/1, I'm getting
```
{
    "page": 1,
    "size": 25,
    "totalCount": 0,
    "records": []
}
```

Is your .net library available in github? Can you mention it's name/link?

**Comment by Suresh-Subedi** [comment]
With semicolon and country code, I do get result back. I must be missing something in the call I made.

**Comment by bluewalk** [comment]
Thanks for testing, I guess I indeed forgot country code, will add 👍

**Comment by bluewalk** [comment]
Assuming that due to the lack of response it's resolved.
