### ISSUE TITLE
Can't get refresh token

### ISSUE THREAD

**Issue by Sharknoon** [bluewalk/lidlplus-php-client#8]
Hello,

I am unable to get the refresh token. When I execute the script `getLidlRefreshToken.js`, I get the following error:

![grafik](https://user-images.githubusercontent.com/16149608/156884581-7084e502-deab-47d6-9945-9251b38736d9.png)

After changing the puppeteer launch options to `headless: false` to debug and see what's happening, it seems to fail at the newly introduced mandatory second factor authentification:

![grafik](https://user-images.githubusercontent.com/16149608/156884654-b96fa457-ec3c-45a7-96fe-6784c18c3fec.png)
(This image gives you the option to validate your lidl account by receiving an code via email or via telephone)

Thank you so much for this great library, unfortunately I cant use it because of the missing refresh token.

**Comment by bluewalk** [comment]
Hi @Sharknoon Thank you very much for looking into this.

The script was actually made by someone else, but I see you've fixed it 👍
